// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB0GziKumJZsUaCKxcCyqmOb9KIqgbUTCk',
    appId: '1:984026038629:web:2d0f7d9ca05ff05fb3a18c',
    messagingSenderId: '984026038629',
    projectId: 'recipeproject-6ec38',
    authDomain: 'recipeproject-6ec38.firebaseapp.com',
    storageBucket: 'recipeproject-6ec38.appspot.com',
    measurementId: 'G-L5QRBJMDFY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA__TMhEfG-tm3qKouP0D9KlxrcdbzRI-w',
    appId: '1:984026038629:android:4fe8f983cb2edde2b3a18c',
    messagingSenderId: '984026038629',
    projectId: 'recipeproject-6ec38',
    storageBucket: 'recipeproject-6ec38.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDnAsqf-fcoTEhViXj9JR0V56Nu_f_zv5o',
    appId: '1:984026038629:ios:5551eedbdeead1d2b3a18c',
    messagingSenderId: '984026038629',
    projectId: 'recipeproject-6ec38',
    storageBucket: 'recipeproject-6ec38.appspot.com',
    iosBundleId: 'com.recipeapp.recipeapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDnAsqf-fcoTEhViXj9JR0V56Nu_f_zv5o',
    appId: '1:984026038629:ios:5551eedbdeead1d2b3a18c',
    messagingSenderId: '984026038629',
    projectId: 'recipeproject-6ec38',
    storageBucket: 'recipeproject-6ec38.appspot.com',
    iosBundleId: 'com.recipeapp.recipeapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB0GziKumJZsUaCKxcCyqmOb9KIqgbUTCk',
    appId: '1:984026038629:web:aabca5959292a74db3a18c',
    messagingSenderId: '984026038629',
    projectId: 'recipeproject-6ec38',
    authDomain: 'recipeproject-6ec38.firebaseapp.com',
    storageBucket: 'recipeproject-6ec38.appspot.com',
    measurementId: 'G-X4W81LW93N',
  );
}
